const fs = require('fs');
let code = fs.readFileSync('apps/hotel-dashboard/src/app/partner/register/page.tsx', 'utf8');

const target = <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">\n                    <div className="relative flex-1">\n                      <Phone className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />\n                      <input\n                        type="tel"\n                        name="phone"\n                        required\n                        value={form.phone}\n                        onChange={handleChange}\n                        disabled={isVerifyingPhone}\n                        placeholder="10-digit mobile number"\n                        \n                        className="w-full rounded-2xl border border-gray-200 py-2 pl-10 pr-4 text-xs font-bold text-gray-900 focus:border-orange-500 focus:outline-none disabled:bg-gray-100"\n                      />\n                    </div>\n                    {!isPhoneVerified ? (\n                      <button\n                        type="button"\n                        onClick={handleVerifyPhoneWithWidget}\n                        disabled={isVerifyingPhone}\n                        className="w-full sm:w-auto shrink-0 flex items-center justify-center rounded-2xl bg-orange-600 px-4 py-2 text-xs font-bold text-white hover:bg-orange-700 disabled:opacity-50"\n                      >\n                        {isVerifyingPhone ? 'Verifying...' : 'Verify Phone Number'}\n                      </button>\n                    ) : (\n                      <span className="w-full sm:w-auto shrink-0 flex items-center justify-center gap-1 rounded-2xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 border border-emerald-200">\n                        <Check className="h-4 w-4" /> Verified\n                      </span>\n                    )}\n                  </div>;

const replace = <div className="relative">\n                    <Phone className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />\n                    <input\n                      type="tel"\n                      name="phone"\n                      required\n                      value={form.phone}\n                      onChange={handleChange}\n                      placeholder="10-digit mobile number"\n                      className="w-full rounded-2xl border border-gray-200 py-2 pl-10 pr-4 text-xs font-bold text-gray-900 focus:border-orange-500 focus:outline-none"\n                    />\n                  </div>;

code = code.replace(target, replace);
fs.writeFileSync('apps/hotel-dashboard/src/app/partner/register/page.tsx', code);
console.log('done');
