version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: foodhub-postgres
    restart: always
    environment:
      POSTGRES_USER: foodhub_user
      POSTGRES_PASSWORD: foodhub_pass
      POSTGRES_DB: foodhub_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: foodhub-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: foodhub-nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
