export declare enum UserRole {
    CUSTOMER = "CUSTOMER",
    HOTEL_STAFF = "HOTEL_STAFF",
    HOTEL_OWNER = "HOTEL_OWNER",
    DELIVERY_PARTNER = "DELIVERY_PARTNER",
    ADMIN = "ADMIN",
    SUPER_ADMIN = "SUPER_ADMIN"
}
export declare enum OrderStatus {
    PENDING = "PENDING",
    ACCEPTED = "ACCEPTED",
    PREPARING = "PREPARING",
    READY_FOR_PICKUP = "READY_FOR_PICKUP",
    DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
    ARRIVED_AT_RESTAURANT = "ARRIVED_AT_RESTAURANT",
    PICKED_UP = "PICKED_UP",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
    REFUNDED = "REFUNDED"
}
export declare enum DeliveryJobStatus {
    AVAILABLE = "AVAILABLE",
    ASSIGNED = "ASSIGNED",
    ARRIVED = "ARRIVED",
    PICKED_UP = "PICKED_UP",
    DELIVERED = "DELIVERED",
    CANCELLED = "CANCELLED"
}
export declare enum PaymentStatus {
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    REFUNDED = "REFUNDED"
}
export declare enum PaymentMethod {
    UPI = "UPI",
    CARD = "CARD",
    NET_BANKING = "NET_BANKING",
    WALLET = "WALLET",
    COD = "COD"
}
export declare enum VehicleType {
    BICYCLE = "BICYCLE",
    SCOOTER = "SCOOTER",
    MOTORCYCLE = "MOTORCYCLE",
    EV_SCOOTER = "EV_SCOOTER"
}
export declare enum DeliveryMode {
    FOODHUB_DELIVERY = "FOODHUB_DELIVERY",
    RESTAURANT_SELF_DELIVERY = "RESTAURANT_SELF_DELIVERY"
}
export declare enum RestaurantDriverStatus {
    AVAILABLE = "AVAILABLE",
    BUSY = "BUSY",
    OFFLINE = "OFFLINE"
}
