import { z } from 'zod';
import { OrderStatus, PaymentStatus, PaymentMethod } from './enums';
export declare const OrderSchema: z.ZodObject<{
    id: z.ZodString;
    orderNumber: z.ZodString;
    customerId: z.ZodString;
    restaurantId: z.ZodString;
    status: z.ZodNativeEnum<typeof OrderStatus>;
    subtotal: z.ZodNumber;
    packagingFee: z.ZodNumber;
    deliveryFee: z.ZodNumber;
    taxAmount: z.ZodNumber;
    discountAmount: z.ZodNumber;
    totalAmount: z.ZodNumber;
    paymentStatus: z.ZodNativeEnum<typeof PaymentStatus>;
    paymentMethod: z.ZodNativeEnum<typeof PaymentMethod>;
    deliveryOtp: z.ZodString;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: OrderStatus;
    createdAt: Date;
    restaurantId: string;
    orderNumber: string;
    customerId: string;
    subtotal: number;
    packagingFee: number;
    deliveryFee: number;
    taxAmount: number;
    discountAmount: number;
    totalAmount: number;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    deliveryOtp: string;
}, {
    id: string;
    status: OrderStatus;
    createdAt: Date;
    restaurantId: string;
    orderNumber: string;
    customerId: string;
    subtotal: number;
    packagingFee: number;
    deliveryFee: number;
    taxAmount: number;
    discountAmount: number;
    totalAmount: number;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    deliveryOtp: string;
}>;
export type IOrder = z.infer<typeof OrderSchema>;
