import { z } from 'zod';
export declare const RestaurantSchema: z.ZodObject<{
    id: z.ZodString;
    ownerId: z.ZodString;
    name: z.ZodString;
    slug: z.ZodString;
    phone: z.ZodString;
    licenseFssai: z.ZodString;
    addressLine: z.ZodString;
    latitude: z.ZodNumber;
    longitude: z.ZodNumber;
    isActive: z.ZodBoolean;
    isOpen: z.ZodBoolean;
    avgRating: z.ZodNumber;
    commissionRate: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    deliveryMode: z.ZodOptional<z.ZodEnum<["FOODHUB_DELIVERY", "RESTAURANT_SELF_DELIVERY"]>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    phone: string;
    ownerId: string;
    name: string;
    slug: string;
    licenseFssai: string;
    addressLine: string;
    latitude: number;
    longitude: number;
    isActive: boolean;
    isOpen: boolean;
    avgRating: number;
    commissionRate?: number | null | undefined;
    deliveryMode?: "FOODHUB_DELIVERY" | "RESTAURANT_SELF_DELIVERY" | undefined;
}, {
    id: string;
    phone: string;
    ownerId: string;
    name: string;
    slug: string;
    licenseFssai: string;
    addressLine: string;
    latitude: number;
    longitude: number;
    isActive: boolean;
    isOpen: boolean;
    avgRating: number;
    commissionRate?: number | null | undefined;
    deliveryMode?: "FOODHUB_DELIVERY" | "RESTAURANT_SELF_DELIVERY" | undefined;
}>;
export type IRestaurant = z.infer<typeof RestaurantSchema>;
export declare const RestaurantDeliveryStaffSchema: z.ZodObject<{
    id: z.ZodString;
    restaurantId: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodOptional<z.ZodString>;
    phone: z.ZodString;
    email: z.ZodOptional<z.ZodString>;
    avatar: z.ZodOptional<z.ZodString>;
    vehicleType: z.ZodOptional<z.ZodString>;
    vehicleNumber: z.ZodOptional<z.ZodString>;
    status: z.ZodEnum<["AVAILABLE", "BUSY", "OFFLINE"]>;
    isActive: z.ZodBoolean;
    createdAt: z.ZodOptional<z.ZodString>;
    updatedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "AVAILABLE" | "BUSY" | "OFFLINE";
    phone: string;
    isActive: boolean;
    restaurantId: string;
    firstName: string;
    vehicleType?: string | undefined;
    vehicleNumber?: string | undefined;
    email?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lastName?: string | undefined;
    avatar?: string | undefined;
}, {
    id: string;
    status: "AVAILABLE" | "BUSY" | "OFFLINE";
    phone: string;
    isActive: boolean;
    restaurantId: string;
    firstName: string;
    vehicleType?: string | undefined;
    vehicleNumber?: string | undefined;
    email?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    lastName?: string | undefined;
    avatar?: string | undefined;
}>;
export type IRestaurantDeliveryStaff = z.infer<typeof RestaurantDeliveryStaffSchema>;
export declare const MenuItemSchema: z.ZodObject<{
    id: z.ZodString;
    restaurantId: z.ZodString;
    categoryId: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    price: z.ZodNumber;
    imageUrl: z.ZodOptional<z.ZodString>;
    isVeg: z.ZodBoolean;
    isAvailable: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    restaurantId: string;
    categoryId: string;
    price: number;
    isVeg: boolean;
    isAvailable: boolean;
    description?: string | undefined;
    imageUrl?: string | undefined;
}, {
    id: string;
    name: string;
    restaurantId: string;
    categoryId: string;
    price: number;
    isVeg: boolean;
    isAvailable: boolean;
    description?: string | undefined;
    imageUrl?: string | undefined;
}>;
export type IMenuItem = z.infer<typeof MenuItemSchema>;
